### ISSUE TITLE
Accelerometer.apk file does not work.

### ISSUE THREAD

**Issue by suhayl-patel** [Nauman3S/iot-starter-android#1]
Dear Developers,

I hope you are well. This is a very fun project. However, I tried to download the Accelerometer.apk file onto my android phone but there appeared a parse error. It mentions that there was a problem while parsing the package when I select the APK file once downloaded onto my android phone. This happened on two phones, and also I have set downloads from unknown sources as true, yet this still occurs.

Any help would be appreciated.

Thanks,
Suhayl

**Comment by Nauman3S** [comment]
Hi @suhayl-patel,

This project was compiled for a specific android phone [two years ago for a tutorial for the IBM developers center](https://developer.ibm.com/tutorials/iot-mobile-phone-iot-device-bluemix-apps-trs/). If you want it to work on your phone, the fastest option would be to just recompile it for your phone using Android Studio.

Regards,
Nauman
