### ISSUE TITLE
Node-RED starter removed from IBM Cloud catalog

### ISSUE THREAD

**Issue by mcorbin-ibm** [Nauman3S/iot-starter-android#3]
In the tutorial on IBM Developer (https://developer.ibm.com/tutorials/iot-mobile-phone-iot-device-bluemix-apps-trs/), Step 2 is for installing and configuring Node-RED.  You provide both IBM Cloud and AWS Cloud options.  The IBM Cloud option is no longer valid, as the Node-RED starter app has been removed from the IBM Cloud catalog.

Would your Node-RED flow still work if we had them install Node-RED locally (https://nodered.org/docs/getting-started/local) instead of into a cloud?

-----

Also, you'll need to update the README file for your repo here to remove the references to installing Node-RED in IBM Cloud and to running the Node-RED app in IBM Cloud.

**Comment by Nauman3S** [comment]
Thank you for pointing out the issue with IBM removing NodeRED from the catalog. You can still use the tutorial and create a VM as mentioned in the "Setting up a baremetal server in IBM Cloud" section of the tutorial and then you can simply deploy NodeRED as you would do on the local machine. Moreover, this tutorial will still work if you deploy NodeRED on the local machine as long as the MQTT broker you use is accessible.

Please note that this repository is not being actively maintained and could have outdated information.
